import Navbar from "@/components/Navbar";
import "./globals.css";
import { Roboto, Roboto_Mono } from "next/font/google";

const roboto = Roboto({
  weight:[ "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});
const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});
 
export const metadata = {
  title: "Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${roboto_mono.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
